name: oadmet_expansion_demo
channels:
  - conda-forge
  - defaults
dependencies:
  - python
  - rdkit
  - pandas
  - scikit-learn
  - matplotlib
  - seaborn
  - jupyterlab
  - numpy
  - lightgbm
  - fsspec
  - huggingface_hub
  - pip:
      - git+https://github.com/PatWalters/useful_rdkit_utils.git@master